// Package sdl ...
// Generated by the zinc tool.  DO NOT EDIT!
// Source: zinc_SDLWindow
package sdl

import (
	"github.com/SirMetathyst/zinc"
	"github.com/veandco/go-sdl2/sdl"
)

// SDLWindowKey ...
const SDLWindowKey uint = 135545206

// SDLWindowData ...
type SDLWindowData struct {
	Window *sdl.Window	
}

// SDLWindowComponent ...
type SDLWindowComponent struct {
	ctx zinc.CTX
	data map[zinc.EntityID]SDLWindowData
}

// NewSDLWindowComponent ...
func NewSDLWindowComponent() *SDLWindowComponent {
	return &SDLWindowComponent{
		data: make(map[zinc.EntityID]SDLWindowData),
	}
}

// SetContext ...
func (c *SDLWindowComponent) SetContext(ctx zinc.CTX) {
	if c.ctx == nil {
		c.ctx = ctx
	}
}

func init() {
	x := NewSDLWindowComponent()
	ctx := zinc.Default().RegisterComponent(SDLWindowKey, x)
	x.SetContext(ctx)
}

// DeleteEntity ...
func (c *SDLWindowComponent) DeleteEntity(id zinc.EntityID) {
	delete(c.data, id)
}

// HasEntity ...
func (c *SDLWindowComponent) HasEntity(id zinc.EntityID) bool {
	_, ok := c.data[id]
	return ok
}

// SetSDLWindow ...
func (c *SDLWindowComponent) SetSDLWindow(id zinc.EntityID, sdlwindow SDLWindowData) {
	if c.ctx.HasEntity(id) {
		if c.HasEntity(id) {
			c.data[id] = sdlwindow
			c.ctx.ComponentUpdated(SDLWindowKey, id)
		} else {
			c.data[id] = sdlwindow
			c.ctx.ComponentAdded(SDLWindowKey, id)
		}
	}
}

// SDLWindow ...
func (c *SDLWindowComponent) SDLWindow(id zinc.EntityID) SDLWindowData {
	return c.data[id]
}

// DeleteSDLWindow ...
func (c *SDLWindowComponent) DeleteSDLWindow(id zinc.EntityID) {
	delete(c.data, id)
	c.ctx.ComponentDeleted(SDLWindowKey, id)
}

// SetSDLWindowX ...
func SetSDLWindowX(e *zinc.EntityManager, id zinc.EntityID, sdlwindow SDLWindowData) {
	v, _ := e.Component(SDLWindowKey)
	c := v.(*SDLWindowComponent)
	c.SetSDLWindow(id, sdlwindow)
}

// SetSDLWindow ...
func SetSDLWindow(id zinc.EntityID, sdlwindow SDLWindowData) {
	SetSDLWindowX(zinc.Default(), id, sdlwindow)
}

// SDLWindowX ...
func SDLWindowX(e *zinc.EntityManager, id zinc.EntityID) SDLWindowData {
	v, _ := e.Component(SDLWindowKey)
	c := v.(*SDLWindowComponent)
	return c.SDLWindow(id)
}

// SDLWindow ...
func SDLWindow(id zinc.EntityID) SDLWindowData {
	return SDLWindowX(zinc.Default(), id)
}

// DeleteSDLWindowX ...
func DeleteSDLWindowX(e *zinc.EntityManager, id zinc.EntityID) {
	v, _ := e.Component(SDLWindowKey)
	c := v.(*SDLWindowComponent)
	c.DeleteSDLWindow(id)
}

// DeleteSDLWindow ...
func DeleteSDLWindow(id zinc.EntityID) {
	DeleteSDLWindowX(zinc.Default(), id)
}

// HasSDLWindowX ...
func HasSDLWindowX(e *zinc.EntityManager, id zinc.EntityID) bool {
	v, _ := e.Component(SDLWindowKey)
	return v.HasEntity(id)
}

// HasSDLWindow ...
func HasSDLWindow(id zinc.EntityID) bool {
	return HasSDLWindowX(zinc.Default(), id)
}